### ISSUE TITLE
Grid Api / Column Api does not work

### ISSUE THREAD

**Issue by chjoshan** [ceolter/ag-grid-react-example#2]
<img width="937" alt="screen shot 2016-02-05 at 14 42 11" src="https://cloud.githubusercontent.com/assets/6425619/12848019/848d263e-cc17-11e5-8a6e-5e7270af7e25.png">

**Comment by ceolter** [comment]
where are you checking this?

https://www.ag-grid.com/best-react-data-grid/index.php

this does ring a bell, i think i fixed this a few days ago, but can't remember exactly where it was broken. i think the example had an error in it (the grid was fine)

**Comment by chjoshan** [comment]
I was testing this example locally. Yes the example on the site works fine.

**Comment by ceolter** [comment]
ok, it is fixed, i am not sure what is wrong with the latest.

i will be doing a release in the coming days, and will be doing full
regression testing, so will get it fixed then.



On 5 February 2016 at 15:14, Joshan Chaudhary <notifications@github.com>
wrote:

> I was testing this example locally. Yes the example on the site works
> fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-react-example/issues/2#issuecomment-180395512>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by chjoshan** [comment]
Great. Thanks :)

**Comment by chjoshan** [comment]
on a side note, in the website section 'Loading CSS' there seems to be a 'dist' folder missing in the alias path if I checked correctly with the source module:

<img width="990" alt="screen shot 2016-02-08 at 21 44 02" src="https://cloud.githubusercontent.com/assets/6425619/12898467/1f7dfa78-cead-11e5-925e-599cb40cc746.png">

**Comment by ceolter** [comment]
thanks. fixed.

On 8 February 2016 at 21:32, Joshan Chaudhary <notifications@github.com>
wrote:

> on a side note, in the website section 'Loading CSS' there seems to be a
> 'dist' folder missing in the alias path if I checked correctly with the
> source module:
>
> [image: screen shot 2016-02-08 at 21 44 02]
> <https://cloud.githubusercontent.com/assets/6425619/12898467/1f7dfa78-cead-11e5-925e-599cb40cc746.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-react-example/issues/2#issuecomment-181560729>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by NetsydeMiro** [comment]
I think this issue is still outstanding on the new release.  

I'm running the ag-grid-react-example on a windows machine, and whenever attempting to show/hide the country column, or select/clear selections (via the operations' respective buttons), the 'this.api' and 'this.columnApi' property references are undefined.  

Screenshot: 

![ag-react-api-issue](https://cloud.githubusercontent.com/assets/3513394/13644477/fced75ca-e5f3-11e5-81dc-064de3e97e4f.png)

**Comment by ceolter** [comment]
are you using the latest ag-grid-react-example version v4.0.0 ?

i checked out latest and tested, and it's working.

the latest is also what i have included on the website and that appears to
be working:
https://www.ag-grid.com/best-react-data-grid/index.php

i do remember something similar about two weeks ago, which i fixed, hence
wondering if you are looking at the latest. or any chance you are not
building correctly and an older version still existing?

On 9 March 2016 at 17:40, NetsydeMiro <notifications@github.com> wrote:

> I think this issue is still outstanding on the new release.
>
> I'm running the ag-grid-react-example on a windows machine, and whenever
> attempting to show/hide the country column, or select/clear selections (via
> the operations' respective buttons), the 'this.api' and 'this.columnApi'
> property references are undefined.
>
> Screenshot:
>
> [image: ag-react-api-issue]
> <https://cloud.githubusercontent.com/assets/3513394/13644477/fced75ca-e5f3-11e5-81dc-064de3e97e4f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-react-example/issues/2#issuecomment-194417793>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by NetsydeMiro** [comment]
The website version is working for me too.  

But I removed the old version from my dev machine, and cloned the new one in a new directory to avoid any conflicts: 

`git clone https://github.com/ceolter/ag-grid-react-example.git`

I'm not sure if it'll help, and it appears that the output contains a lot of formatting & control characters, but attached is the output from `npm list` & `npm start` when I run them from within the new ag-grid-react-example directory:  

[npm_list.txt](https://github.com/ceolter/ag-grid-react-example/files/166284/npm_list.txt)

[npm_start.txt](https://github.com/ceolter/ag-grid-react-example/files/166285/npm_start.txt)

I may try to troubleshoot a bit later, but I'm new to webpack and haven't had the chance to step through the code yet.  For now I'll keep using the prior version's bundle.

**Comment by ceolter** [comment]
crap, i don't believe it. i had a local change i didn't check it - normally intelij colors changed files, didn't this time, never seen that before no idea why, basically i'm saying sorry and blaming intllij.

please update.

the prob was, the grid even 'ready' is now called 'gridReady' (something i changed a few weeks ago)

**Comment by chjoshan** [comment]
I did not check later after closing the issue. Thanks anyways for the quick response.

**Comment by NetsydeMiro** [comment]
Works for me now, thanks for the quick fix.  Great work on this grid; cheers!
